// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLmbrgWYFTWUTHGCBbtrh18QFPTl_eI8',
    appId: '1:925797515021:web:b5e50321ab186378a7ba44',
    messagingSenderId: '925797515021',
    projectId: 'todolistapp-199ed',
    authDomain: 'todolistapp-199ed.firebaseapp.com',
    storageBucket: 'todolistapp-199ed.appspot.com',
    measurementId: 'G-BLD8J4W565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwfsEhHP-C36dNPb83x6scVdcweO3EkGg',
    appId: '1:925797515021:android:0353b8230d8032fca7ba44',
    messagingSenderId: '925797515021',
    projectId: 'todolistapp-199ed',
    storageBucket: 'todolistapp-199ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA35ynZugUBqtxl__Af-eBxNIfohynXnUI',
    appId: '1:925797515021:ios:9b58343a58e5a891a7ba44',
    messagingSenderId: '925797515021',
    projectId: 'todolistapp-199ed',
    storageBucket: 'todolistapp-199ed.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA35ynZugUBqtxl__Af-eBxNIfohynXnUI',
    appId: '1:925797515021:ios:9b58343a58e5a891a7ba44',
    messagingSenderId: '925797515021',
    projectId: 'todolistapp-199ed',
    storageBucket: 'todolistapp-199ed.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArLmbrgWYFTWUTHGCBbtrh18QFPTl_eI8',
    appId: '1:925797515021:web:546dd0ec05c1c77ea7ba44',
    messagingSenderId: '925797515021',
    projectId: 'todolistapp-199ed',
    authDomain: 'todolistapp-199ed.firebaseapp.com',
    storageBucket: 'todolistapp-199ed.appspot.com',
    measurementId: 'G-5P8R4HBB2F',
  );

}